# ---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/theteolog/homepage-config

- VPN:
    - V2RayA:
        - abbr: VA
          href: http://edi.home:2017/
    - 3x-ui DE:
        - abbr: DE
          href: https://{{HOMEPAGE_VAR_DENODE_HOST}}:{{HOMEPAGE_VAR_DENODE_PORT}}/{{HOMEPAGE_VAR_DENODE_SEED}}/panel/
    - 3x-ui RU:
        - abbr: RU
          href: https://{{HOMEPAGE_VAR_RUNODE_HOST}}:{{HOMEPAGE_VAR_RUNODE_PORT}}/{{HOMEPAGE_VAR_RUNODE_SEED}}/panel/

- Home Management:
    - UK Volgogradskaya:
        - abbr: V220
          href: https://uk-mvolga.ru/
    - UK Savkova:
        - abbr: S8UK
          href: http://www.ukgreen.ru/
    - UK Savkova counters:
        - abbr: S8C
          href: https://cabinet.rc-online.ru/sign_in
