---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/theteolog/homepage-config

- VPN:
    - V2RayA:
        - abbr: VA
          href: http://edi.home:2017/
    - Marzban:
        - abbr: MA
          href: http://teo-vpn:8000/dashboard/

- Social:
    - V220:
        - abbr: V220
          href: https://uk-mvolga.ru/
    - S8UK:
        - abbr: S8UK
          href: http://www.ukgreen.ru/
    - S8C:
        - abbr: S8C
          href: https://cabinet.rc-online.ru/sign_in